plot(1:100,sin(2*pi*(1:100)/20))
xlabel('x axis')
ylabel('y axis')
axis([1 100 -1.5 1.5])
legend('sinus')

matlab2tikz(['tikz/example.tikz'],...
    'width','\figurewidth',...
    'height','\figureheight',...
    'extraAxisOptions','clip mode=individual,transpose legend,legend columns=2,legend style={at={(0,1)},anchor=north west,draw=black,fill=white,legend cell align=left}',...
    'extraTikzpictureOptions','font=\footnotesize',...
    'checkForUpdates',false);